# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OSSLibrary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OSSLibrary
  pod 'Gecco'


  target 'OSSLibraryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OSSLibraryUITests' do
    # Pods for testing
  end

end
