# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

  def common_pods
    # Pods for All
    pod 'Google-Mobile-Ads-SDK'
    pod 'GoogleAnalytics'
    pod 'GoogleUtilities'
    pod 'Firebase/Core'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Performance'
    pod 'Firebase/Messaging'
    pod 'SwiftyStoreKit'
    pod 'Gecco'
    pod 'EAIntroView'
    pod 'MXParallaxHeader'
#    pod 'Firebase/AdMob'
#    pod 'RealmSwift', ' ~> 10.21'
#    pod 'NeuKit'
#    pod 'EMTNeumorphicView'
  end

  target 'Paciolist' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!

    # Pods for Accountant
    common_pods
  end

  target 'PaciolistSTG' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!

    # Pods for Accountant
    common_pods
  end

#  target 'AccountantTests' do
#    inherit! :search_paths
#    # Pods for testing
#    common_pods
#  end

#  target 'AccountantUITests' do
#    # Pods for testing
#    common_pods
#  end

  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
        File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
      end
    end
  end
