# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

  def common_pods
    # Pods for All
    pod 'Google-Mobile-Ads-SDK', '8.13.0'
    pod 'GoogleAnalytics'
    pod 'GoogleUtilities', '7.7.0'
#    pod 'Firebase/AdMob'
    pod 'Firebase/Core'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Performance'
    pod 'SwiftyStoreKit'
#    pod 'RealmSwift', ' ~> 10.21'
#    pod 'NeuKit'
#    pod 'EMTNeumorphicView'
    pod 'Gecco'
    pod 'EAIntroView'
    pod "MXParallaxHeader"
    pod 'Alamofire', '5.6.1'
  end

  target 'Paciolist' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!

    # Pods for Accountant
    common_pods
  end

  target 'PaciolistSTG' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!

    # Pods for Accountant
    common_pods
  end

#  target 'AccountantTests' do
#    inherit! :search_paths
#    # Pods for testing
#    common_pods
#  end

#  target 'AccountantUITests' do
#    # Pods for testing
#    common_pods
#  end

  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
