name: CI

on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2.0'
    
      - name: UnitTests
        run: xcodebuild test -workspace Accountant.xcworkspace -scheme Paciolist -sdk iphonesimulator -destination platform='iOS Simulator,name=iPhone 12,OS=16.1'
